# Header
menu:
  主页: /
  列表: /archives/

# SubNav
subnav:
  # RSS plugin: https://github.com/hexojs/hexo-generator-feed
  # Encrypt email 加密邮件地址 http://tool.chacuo.net/commonhideinfo
  Email: "mailto:micro-tech@foxmail.com"
  GitHub: "https://github.com/crzidea"
  #V2EX: "#"
  #RSS: "/atom.xml"
  #知乎: "zhihu"
  #豆瓣: "douban"
  #Facebook: "#"
  #Google: "#"
  #Twitter: "#"
  #LinkedIn: "#"
  新浪微博: "http://weibo.com/crzidea"
  QQ: "http://wpa.qq.com/msgrd?v=3&uin=133683737&site=qq&menu=yes"
  #微信: "Wechat"
  #PayPal: ""
  #StackOverflow: "#"
  #Instagram: "#"
  #Flickr: "#"

# Customize feed link 自定义订阅地址
rss: /atom.xml

# "5": show images form bg-1.jpg to bg-5.jpg in `/yelee/source/background/`
# "5": 显示`/yelee/source/background/`文件夹中 bg-1.jpg 到 bg-5.jpg 这5张图片
# "0": white-gray background | 淳朴灰白背景
background_image: 0

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: false

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: 'UA-81807912-1'
favicon: /favicon.png

#你的头像url
avatar: /img/avatar.png

#是否开启分享
share: true

#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#注册多说后，地址前面的就是你的 duoshuo-key http://duoshuo-key.duoshuo.com
duoshuo: crzidea

#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  Hexo: https://hexo.io
  GitHub: https://pages.github.com/
  MOxFIVE: http://moxfive.xyz/

#是否开启“关于我”。
#不开启——
aboutme: false
#开启——
#aboutme: 专注于前端

#是否显示边栏中的搜索框
#Search Box in left column
#search_box: true
